# Use root/example as user/password credentials
version: "3.7"

services:
  fronted:
    image: chatfrontend
    build: .
    restart: always
    ports:
      - 4200:80
    depends_on:
      - chatserver

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pw
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  chatserver:
    image: chatserver
    build: ../backend
    depends_on:
      - mongo
    restart: always
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      # Port für die API
      API_PORT: 3000
      API_CORS_ORIGIN: "http://localhost:4200" #Bei bedarf anpassen

      # Port für Web Sockets
      WEB_SOCKET_PORT: 8080

      # MongoDB-Zugangsdaten
      DATABASE_HOST: "mongodb://mongo:27017"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "pw"

      # Schlüssel zum Signieren der JWTs
      JWT_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKAIBAAKCAgEAjz/uhKxHmJvjkBqUBzTycF41v5jSAsT/beplXMuPUuG0nAPw
        Yzlk4CPGFem1ZT+CoJ58wkdGJK0v7QUjjWaVK9K46NSqY5tPfQkqI0ZDlgcdEZX6
        XCam66ZjmiUhlAZUMWTZL1MqteiNZo51/hj5xh2c26R9oQvfwLPKmOco8wmRR6yu
        C68Zpd5n3aQLksNfiOjDOeK6YWu176cHxPeimDWYrqJplUN0DoQrZdP9kDocJMFR
        j3P46Zq33IPm/+e91AQc5hLrgVTx7FabWQVIdmIad8dkvw3Tjrq8E3FJPU9P4QKH
        oaA+rlyvfQdFE17hX+mmeNYrl78XvoHDjJUYcsooT4vF0NEym+aKtN5fx6d9dKd+
        KJVRr6mUc5tWbSLad4r8W/3sFsQyeglAQZsXt4gnQCRUOZ52qy3nyfk227KfHD6K
        O4JNQTD0+8P3qEcptoVe5xUpQnCy/vScOilWNYdJCzJDsdsaEbWRe6VfoudPHrfc
        v02hMeVyoi4g1DRuL2i07AU/eQer9UzM68abeBRDrvgnGLUf/nNsAFhxIGk3fN3R
        Djz0sS7rG2RmibuZJl3hVLHeR9b3Ssds1bV58G42yQO2TrColxHizJzB4BANnI/G
        01dmUOxuNRMQx2ofphzDGHeoGd+C8QSeL+ukzpJCVeAbMR3AcfaJZZvDQJkCAwEA
        AQKCAgBhm756yKlAY3h8CKA1CO7pgkg9dXQkTvd9fenzgQD4CLN4W3bBJaqGz9l5
        tPXVN6FasKNx/f7dnuS5LHc9MlkSs1Mr0z0HAhz3pfcAcjA7Wj2Ebh1aDTxP9eCI
        eCSZKHbV8VHL3W+M5Bj1eL0Nlxca17K6NysjQWQFenziEyDj+fD0VcWCUJ25WAKO
        E+mO53GBaJkeKE+3ch1WXwn8PICeFmcjF6e5/WxnN8gaaoisbewfX1qj1PIWu0Xt
        DDOqy82dWfAXFW1Dgw4VbC4OSntFrzM5yrPrOxCcgMEGvnqZPCHBwGeKyhXr2Vv6
        Zam7uTr4j8zPKaAqlhsnxGPqtu0gu9hYzFS3ugJEezkTvZj7opndMYdK2occlsr4
        kNCiNMBGK9uvThonaA6FdFCQMUYC9P1xSHS1AQaaNQkK5sYCqNyFNRO+dtEXEWBh
        gUadQ9Y/aWhBnG2/6LAdo8ZYbANsamjtoqOpOpHmAvHGI+gvBAQgEnIYUMSsuqUt
        JFZTI00q6GosjJMBrtX6GMlNaohZzT7cmwHxXNWtynghUYgSJyR1GNZnAnLuABQx
        vMxXqywkJ8MLSHMxFPW/sFXYpc1mcQAlrBSxcTAI3Esm1izs8cuo8fv0qgPeXUcS
        uIPpk3OLK9vOHdxWZWViJHa4DAv4HJPZVU2P1Ie9Qu2pj8uXwQKCAQEA+zvOQ4Pv
        yvj5DTxAPGtfKUctvpdt0kMOm7tqK43OuMkB+2hQHkghQGpmgTMmZk6Hmcue/3bw
        WPa/VOGEMLPAbcuad+Z9YErUBG1MeiDIDoPpr2jpr5PyE7v42yKQ/5fuDMxttY8v
        6sn4LAy9YmX1pNEADYFtM3mo+0uxok1++QQu7VjkSAOF5LT7ibTfF8LAUi+raeTU
        pE5vzsbt2TCNYi7v0oGL8OT2bEiW/8+7NWu3IQzinB1jE3GZFGQjzMvxD64EfPk/
        mFRSsJqJRF+hBp84QxjWS8fp/4Nr59nMht0Z8J8pueEPEhRkPolW4+oDfXh9DZlW
        fQyOD/5zy5WRuwKCAQEAkferLEvDCb68RUdmGiGTK3IsbZltbb49Fm0sf8hTiYPe
        DlRTi5FOv7wTJfbiJMpa+l8UORnWlZlynUs/uwYIkFG6uh0qB97xDtxUMpY4H8U+
        HbyCAIH7NPkwXJgLBLX5zRlTCHvwG9FVrhJP4sReZj8skdqprn0JDl82kX4UPJrP
        Gkl5QQsSOGJVICx34rqbkSPTWCZ+l5ySZyf8Vhs4xrKJNRIOH+Kw1kBFX44ovKOr
        ej5G6LneNGUDks6snSgaWFnb2H8RcjWqZcDz/zUCO0eH/lHcLJcbnS2m9VXJf5K4
        wOAu++fyTWkA1tDmluMJOH31ND6u3RripaG2TJ4XuwKCAQEA2HjGmEwVkOmIBsx0
        eNr3auTG2KM34GUhMDSDHbYZegTQrWRLLFxwMkW7vvVoz9w4YN8fR/We0LkDUUrj
        kOdBFhnKJie2vgKbvpjCvbSDTGaDMz4NpNiwTCq6GW8mSuUJG4QFv9v5qK+QI7xy
        bld2GiZvijOL+T+Jx8WH8FYf4sak/KOMRzSp6M+8sQHk/F81QVuLsjmWs2BWXG/x
        vyNjn0bcI6C2CMHwRosheJfwMe53I4Yrt+JmXPmTsgs7AZp0QlNp0JkfH80AVuVB
        A2X2pHMKkl3TQAaobB48GtECtu3KDRfHZz8xsh1Z5ryF3unjSfhIoDAQYr0vpz5T
        XgapQwKCAQB5H+sD++5htMvoNUJNptTH9ZtWaz26FmX8qSWG98YSU8G9ZE5bf324
        byn4k/C+lMiAAMv4Qi+lvkq0qc+9s1kB4UAw1qidFWw1Z7HatHroKjXMWTQLldDN
        +YYfH+/svdEHV99mJ+psOv59TybJRygKcpvagHfTmmAcc/gFLXk/fTskVhnvVm+N
        KFP5Oc1V8IHNI8xp1q+vwbZfMXgcP8SSZW6kAlKENQmHEJhAnefB+ZL/ApS25B22
        nqgjd6sXUkLiU9axxWfFvTCj9UTD3sn2RPpdmLI6sj2w5UQpS0HEwgzbyGxUjvmr
        MNoIaBsg1E8/eI40B1v1kCzJQvLSi1GnAoIBAGp85UUMkVXxqTFNL4EwtEezxbnn
        IOgAuN1dbrQnfNUlKSDfFI5EPJVYrw8/NoETcNq7Z5LN97e8/Rg1sdHnqPUwcu0g
        ql2Irih0l5bL/z1q9BVRtQLrM8sqJxSLmSes19htiKbb+jtOJDCiqbIzyRv4Z+hh
        rTPCwysw1W9lXjm682JRTSswCrVcQy9wLSfHuLAaaQJP8eFA8NjJT1OTbcXe6BGe
        QUZE06cXknNlwIdN5JqDsqujKLolwc6SKU6TAvlu8ec4BQvIiLc4NPvZXLnqN9JS
        Y6jae/hmQF62KLmoW22+NVfLKpBxiw0y5Md2iMvLCuul9qY02Rdh5/h0hBk=
        -----END RSA PRIVATE KEY-----
volumes:
  mongodbdata:
